version: '3.8'

services:
  auth-api:
    build: .
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-tiny-heart-acx03kbv-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000

      # Email Configuration
#      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
#      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
    restart: unless-stopped